package com.novel.cn.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.novel.cn.db.SearchHistory;
import com.novel.cn.db.Readcord;

import com.novel.cn.db.SearchHistoryDao;
import com.novel.cn.db.ReadcordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig readcordDaoConfig;

    private final SearchHistoryDao searchHistoryDao;
    private final ReadcordDao readcordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        readcordDaoConfig = daoConfigMap.get(ReadcordDao.class).clone();
        readcordDaoConfig.initIdentityScope(type);

        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        readcordDao = new ReadcordDao(readcordDaoConfig, this);

        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(Readcord.class, readcordDao);
    }
    
    public void clear() {
        searchHistoryDaoConfig.clearIdentityScope();
        readcordDaoConfig.clearIdentityScope();
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public ReadcordDao getReadcordDao() {
        return readcordDao;
    }

}
