package com.novel.cn.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.novel.cn.db.Readcord;
import com.novel.cn.db.SearchHistory;
import com.novel.cn.view.readpage.BookChapterBean;

import com.novel.cn.db.ReadcordDao;
import com.novel.cn.db.SearchHistoryDao;
import com.novel.cn.db.BookChapterBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig readcordDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig bookChapterBeanDaoConfig;

    private final ReadcordDao readcordDao;
    private final SearchHistoryDao searchHistoryDao;
    private final BookChapterBeanDao bookChapterBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        readcordDaoConfig = daoConfigMap.get(ReadcordDao.class).clone();
        readcordDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        bookChapterBeanDaoConfig = daoConfigMap.get(BookChapterBeanDao.class).clone();
        bookChapterBeanDaoConfig.initIdentityScope(type);

        readcordDao = new ReadcordDao(readcordDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        bookChapterBeanDao = new BookChapterBeanDao(bookChapterBeanDaoConfig, this);

        registerDao(Readcord.class, readcordDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(BookChapterBean.class, bookChapterBeanDao);
    }
    
    public void clear() {
        readcordDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        bookChapterBeanDaoConfig.clearIdentityScope();
    }

    public ReadcordDao getReadcordDao() {
        return readcordDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public BookChapterBeanDao getBookChapterBeanDao() {
        return bookChapterBeanDao;
    }

}
